version: 2
updates:
- package-ecosystem: composer
  directory: "/backend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: development
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: development
  ignore:
      # Ignore quasar major version updates (requires Vue 3 upgrade)
      - dependency-name: "quasar"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@quasar/app"
        update-types: ["version-update:semver-major"]
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: development
- package-ecosystem: npm
  directory: "/docs"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: development
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: development
