majestic:
  description: Create container to proxy Majestic Jest UI.
  template:
    services:
      majestic:
        type: node:14
        build:
          - cd client && yarn
        port: 4000
        command: "cd client && yarn test:unit:ui"
        scanner: false
    proxy:
      majestic:
        - majestic.pilcrow.lndo.site:4000
cypress:
  description: Install the cypress test runner and tooling command.
  template:
    services:
      cypress:
        type: node:16
        overrides:
          image: "cypress/base:16"
          environment:
            ELECTRON_EXTRA_LAUNCH_ARGS: "--force-prefers-reduced-motion"
    tooling:
      cypress:
        service: cypress
        dir: /app/client
        cmd: yarn cypress
mailhog:
  description: Catch mail output from Pilcrow with mailhog.
  template:
    services:
      mailhog:
        type: mailhog:v1.0.0
        hogfrom:
          - appserver
    proxy:
      mailhog:
        - mailhog.pilcrow.lndo.site
