cypress:
  description: Install the cypress test runner and tooling command.
  template:
    services:
      cypress:
        type: node:18
        overrides:
          image: "cypress/base:18.16.1"
          environment:
            ELECTRON_EXTRA_LAUNCH_ARGS: "--force-prefers-reduced-motion"
    tooling:
      cypress:
        service: cypress
        dir: /app/client
        cmd: yarn cypress
mailhog:
  description: Catch mail output from Pilcrow with mailhog.
  template:
    services:
      mailhog:
        type: mailhog:v1.0.0
        hogfrom:
          - appserver
    proxy:
      mailhog:
        - mailhog.pilcrow.lndo.site
