version: '3'
services:
  client:
    image: pilcrow/web:latest
  phpfpm:
    image: pilcrow/fpm:latest
    environment:
      DB_DATABASE: pilcrow
      DB_HOST: mysql
      DB_USERNAME: pilcrow
      DB_PASSWORD: pilcrow
      APP_HOSTNAME: localhost
      APP_ENV: testing
      APP_DEBUG: true
      MAIL_FROM_ADDRESS: noreply@pilcrow.dev
      MAIL_FROM_NAME: "CITester"
      MAIL_MAILER: log
  mysql:
    environment:
      MYSQL_DATABASE: pilcrow
      MYSQL_USER: pilcrow
      MYSQL_PASSWORD: pilcrow
