version: '3'
services:
  client:
    environment:
      FPM_HOST: phpfpm:9000
    build:
      image: ghcr.io/mesh-research/pilcrow/web:latest
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - phpfpm
      - mysql
    expose:
      - 8888
  phpfpm:
    env_file:
      - .env
    environment:
      WAIT_HOSTS: mysql:3306
    build:
      image: ghcr.io/mesh-research/pilcrow/fpm:latest
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.40
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
