name: Build
inputs:
    target:
        description: "package to build"
        required: false
runs:
    using: "composite"
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Find Tag
          id: tagger
          shell: bash
          run: |
              echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT
              echo "url=https://github.com/MESH-Research/CCR/commits/${GITHUB_SHA}" >> $GITHUB_OUTPUT
              echo "date=$(git show -s --format=%cI ${GITHUB_SHA})" >> $GITHUB_OUTPUT
        - uses: docker/setup-buildx-action@v2
        - name: Docker meta (FPM)
          id: docker-meta-fpm
          uses: docker/metadata-action@v4
          with:
            images: |
              ghcr.io/${{ github.repository_owner }}/pilcrow/fpm
            tags: |
              type=ref,event=pr
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=sha,enable=${{ github.event_name == 'push' }}
            bake-target: fpm
        - name: Docker meta (WEB)
          id: docker-meta-web
          uses: docker/metadata-action@v4
          with:
            images: |
              ghcr.io/${{ github.repository_owner }}/pilcrow/web
            tags: |
              type=ref,event=pr
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=sha,enable=${{ github.event_name == 'push' }}
            bake-target: web
        - name: Build and push
          uses: docker/bake-action@v4
          with:
            pull: true
            targets: ${{ inputs.target }}
            files: |
              ./docker-bake.hcl
              ${{ steps.docker-meta-fpm.outputs.bake-file }}
              ${{ steps.docker-meta-web.outputs.bake-file }}
        - id: build
          uses: docker/build-push-action@v4
          with:
              context: ${{ fromJSON('{"fpm":"backend","web":"client"}')[inputs.package] || inputs.package }}
              outputs: ${{ (!inputs.push) && format('{0}{1}{2}', 'type=docker,dest=/tmp/', inputs.package, '.tar') || '' }}
              push: ${{ inputs.push && true || false }}
              build-args: |
                  VERSION=${{ steps.tagger.outputs.version }}
                  VERSION_DATE=${{ steps.tagger.outputs.date}}
                  VERSION_URL=${{ steps.tagger.outputs.url }}
              tags: ${{ inputs.tags && inputs.tags || format('{0}{1}{2}', 'pilcrow/', inputs.package, ':latest') }}
              labels: ${{ inputs.labels }}
              cache-from: type=local,src=/tmp/.buildx-cache
              cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        - name: Move cache
          shell: bash
          run: |
              rm -rf /tmp/.buildx-cache`
              mv /tmp/.buildx-cache-new /tmp/.buildx-cache
        - name: Upload artifact
          if:  ${{ !inputs.push }}
          uses: actions/upload-artifact@v3
          with:
              name: ${{ inputs.package }}
              path: /tmp/${{ inputs.package }}.tar
