name: Build
inputs:
    package:
        description: "package to build"
        required: true
    tags:
        description: "tags to apply to the image"
        required: false
    labels:
        description: "labels to apply to the image"
        required: false
    push:
        description: "push the image to the registry"
        required: false
runs:
    using: "composite"
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Find Tag
          id: tagger
          shell: bash
          run: |
              echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT
              echo "url=https://github.com/MESH-Research/CCR/commits/${GITHUB_SHA}" >> $GITHUB_OUTPUT
              echo "date=$(git show -s --format=%cI ${GITHUB_SHA})" >> $GITHUB_OUTPUT
        - uses: docker/setup-buildx-action@v2
        - id: build
          uses: docker/build-push-action@v4
          with:
              context: ${{ fromJSON('{"fpm":"backend","web":"client"}')[inputs.package] || inputs.package }}
              outputs: ${{ (!inputs.push) && format('{0}{1}{2}', 'type=docker,dest=/tmp/', inputs.package, '.tar') || '' }}
              push: ${{ inputs.push && true || false }}
              build-args: |
                  VERSION=${{ steps.tagger.outputs.version }}
                  VERSION_DATE=${{ steps.tagger.outputs.date}}
                  VERSION_URL=${{ steps.tagger.outputs.url }}
              tags: ${{ inputs.tags && inputs.tags || format('{0}{1}{2}', 'pilcrow/', inputs.package, ':latest') }}
              labels: ${{ inputs.labels }}
        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
              name: ${{ inputs.package }}
              path: /tmp/${{ inputs.package }}.tar
