name: "Load Image Artifact"
runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v3
        - uses: actions/download-artifact@v3
          with:
              name: Docker Images
              path: /tmp
        - run: |
              docker load --input /tmp/fpm.tar.gz
              docker load --input /tmp/web.tar.gz
              docker image ls
          shell: bash
