name: docs
services:
  dev:
    type: node:18
    build:
      - yarn
    port: 5173
    ssl: true
    command: yarn docs:dev --host
tooling:
  yarn:
    service: dev
    cmd: yarn
proxy:
  dev:
    - hostname: docs.pilcrow.lndo.site
      port: 5173
      ssl: true
