name: CI
on:
  pull_request:

concurrency:
  group: tests-${{ format('{0}-{1}', github.head_ref || github.run_number, github.job) }}
  cancel-in-progress: true

jobs:
  build-fpm:
    name: "Backend"
    uses: ./.github/workflows/container-build.yml
    with:
      package: fpm
  build-web:
    name: "Client"
    uses: ./.github/workflows/container-build.yml
    with:
      package: web
  client-unit-test:
    name: "Client / Unit Test"
    needs: [build-web]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: client/yarn.lock
      - run: cd client && yarn install
      - run: cd client && yarn test:unit:ci
  backend-unit-test:
    name: Backend / Unit Test
    needs: [build-fpm]
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: fpm
          path: /tmp
      - run: |
          docker load --input /tmp/fpm.tar
          sudo systemctl start mysql.service
          mysql -uroot -proot -e "CREATE schema pilcrow;"
      - uses: addnab/docker-run-action@v3
        with:
          options: >
            -e DB_DATABASE=pilcrow
            -e DB_HOST=localhost
            -e DB_USERNAME=root
            -e DB_PASSWORD=root
            -e APP_ENV=testing
            -e APP_HOSTNAME=localhost
          image: pilcrow/fpm:latest
          run: |
            composer install
            ./artisan migrate:fresh --seed
            ./artisan test"
  e2e:
    name: "E2E Test"
    needs: [build-fpm, build-web]
    uses: ./.github/workflows/test-e2e.yml
    secrets: inherit
  lint-php:
    name: PHP Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install
      - name: Check PHP
        run: composer lint
  lint-js:
    name: JS Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: |
          cd client && yarn install
      - name: Check JS
        run: cd client && yarn lint
  lint-md:
    name: MD Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: yarn install
      - name: Check MD
        run: yarn lint:md
