name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - renovate/*
      - wreality/gha-concurrency

concurrency:
  group: ci-${{ github.sha }}
  cancel-in-progress: true

jobs:
  client-unit-test:
    name: "Client / Unit Test"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: client/yarn.lock
      - run: cd client && yarn install
      - run: cd client && yarn test:unit:ci
  build-images:
    name: "Build"
    strategy:
      matrix:
        package: [fpm, web]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-image
        with:
          package: ${{ matrix.package }}
  backend-unit-test:
    name: Backend / Unit Test
    needs: [build-images]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/start-stack
      - run: docker compose exec -T phpfpm ./artisan test
      - run: docker compose down
  e2e:
    name: "E2E Test"
    needs: [build-images]
    uses: ./.github/workflows/do-test-e2e.yml
    secrets: inherit
  lint-php:
    name: PHP Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install
      - name: Check PHP
        run: composer lint
  lint-js:
    name: JS Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: |
          cd client && yarn install
      - name: Check JS
        run: cd client && yarn lint
  lint-md:
    name: MD Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: yarn install
      - name: Check MD
        run: yarn lint:md
  publish:
    name: "Publish (master branch only)"
    runs-on: ubuntu-20.04
    needs: [e2e, backend-unit-test, client-unit-test]
    strategy:
      matrix:
        package: [fpm, web]
    if: github.event_name == 'push'  && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/mesh-research/pilcrow/${{ matrix.package }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,enable=true
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/load-image
        with:
          name: ${{ matrix.package }}
      - uses: ./.github/actions/build-image
        with:
          package: ${{ matrix.package }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
