name: Build
on:
  workflow_call:
    inputs:
      package:
        type: string
        description: "Package to build"
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    name: "Build"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Context
        id: context
        run: |
          if [ "$PACKAGE" = "web" ]; then
              echo "context=client" >> $GITHUB_OUTPUT
          else
              echo "context=backend" >> $GITHUB_OUTPUT
          fi
          if [[ "$PACKAGE" == *"dev"* ]]; then
              echo "nodev=0" >> $GITHUB_OUTPUT
          else
              echo "nodev=1" >> $GITHUB_OUTPUT
          fi
        env:
          PACKAGE: ${{ inputs.package }}
      - name: Find Tag
        id: tagger
        run: |
          echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT
          echo "url=https://github.com/MESH-Research/CCR/commits/${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "date=$(git show -s --format=%cI ${GITHUB_SHA})" >> $GITHUB_OUTPUT
      - uses: docker/setup-buildx-action@v2
      - id: build
        uses: docker/build-push-action@v4
        with:
          context: ${{ steps.context.outputs.context }}
          outputs: type=docker,dest=/tmp/${{ inputs.package }}.tar
          build-args: |
            COMPOSER_NO_DEV=${{ steps.context.outputs.nodev }}
            VERSION=${{ steps.tagger.outputs.version }}
            VERSION_DATE=${{ steps.tagger.outputs.date}}
            VERSION_URL=${{ steps.tagger.outputs.url }}
          tags: pilcrow/${{ inputs.package }}:latest
      - name: Image digest
        run: echo ${{ steps.build.outputs.digest }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.package }}
          path: /tmp/${{ inputs.package }}.tar
