name: deploy to production
on:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy to Reclaim Cloud
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd ccr-staging
            ./redeploy.sh
          host: ${{ secrets.STAGING_HOST }}
          port: ${{ secrets.STAGING_PORT }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.PRIVATE_KEY}}
