name: Build
on:
  workflow_call:
    inputs:
      package:
        description: "package to build"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04
    name: "Build"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Find Tag
        id: tagger
        run: |
          echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT
          echo "url=https://github.com/MESH-Research/CCR/commits/${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "date=$(git show -s --format=%cI ${GITHUB_SHA})" >> $GITHUB_OUTPUT
      - uses: docker/setup-buildx-action@v2
      - id: build
        uses: docker/build-push-action@v4
        with:
          context: ${{ fromJSON('{"fpm":"backend","web":"client"}')[inputs.package] || inputs.package }}
          outputs: type=docker,dest=/tmp/${{ inputs.package }}.tar
          build-args: |
            VERSION=${{ steps.tagger.outputs.version }}
            VERSION_DATE=${{ steps.tagger.outputs.date}}
            VERSION_URL=${{ steps.tagger.outputs.url }}
          tags: pilcrow/${{ inputs.package }}:latest
      - name: Image digest
        run: echo ${{ steps.build.outputs.digest }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.package }}
          path: /tmp/${{ inputs.package }}.tar
