name: "Test: E2E"
on:
  workflow_call:
jobs:
  playwright:
    runs-on: ubuntu-20.04
    name: "Playwright"
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4, 5, 6]
        shardTotal: [6]
    defaults:
      run:
        working-directory: playwright
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - uses: ./.github/actions/start-stack
      - run: yarn install && yarn playwright install --with-deps
      - name: Run Playwright
        run: yarn playwright test --project chromium --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        env:
          BASEURL: http://localhost:8888/
      - run: docker compose down
      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: "playwright/screenshots"
          retention-days: 14
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-${{ matrix.shardIndex }}
          path: playwright/playwright-report/
          retention-days: 30
