name: "Test: E2E"

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]
jobs:
  cypress:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    name: "Cypress.io"
    steps:
      - name: Install Lando
        run: wget -nv https://files.devwithlando.io/lando-stable.deb && sudo dpkg -i --ignore-depends=docker-ce lando-stable.deb
      - uses: actions/checkout@v2
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: backend/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Cache Node packages
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Enable Cypress config
        run: lando extras e cypress && lando start && lando cypress install
      - name: Migrate Database
        run: lando artisan migrate
      - name: Execute Cypress Tests
        run: lando cypress run
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: client/test/cypress/screenshots
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: client/test/cypress/videos
      - name: Destroy lando containers
        run: lando destroy -y
